"use client";
import React from 'react';
import { motion } from 'framer-motion';
import { useIntelligence } from '../context/IntelligenceContext';
import MapWrapper from './MapWrapper';

export default function GeospatialIntelligence() {
    const { selectedRegion, setSelectedRegion, isLoading } = useIntelligence();

    return (
        <section className="space-y-6">
            <h2 className="text-xl font-sans font-bold text-[var(--navy-premium)] px-2">
                Strategic Territory Assessment
            </h2>

            <div className="flex flex-col lg:flex-row gap-8">
                
                {/* 45% Width Map Area */}
                <div className="w-full lg:w-[45%] h-[600px]">
                    <div className="w-full h-full rounded-2xl overflow-hidden border border-[var(--slate-soft)] shadow-sm relative bg-white">
                        <MapWrapper 
                            constituency={selectedRegion.name} 
                            onRegionSelect={setSelectedRegion}
                            selectedRegionId={selectedRegion.id}
                        />
                        
                        {/* Overlay loading state */}
                        {isLoading && (
                            <div className="absolute inset-0 bg-white/50 backdrop-blur-sm z-[500] flex items-center justify-center">
                                <div className="flex flex-col items-center gap-3">
                                    <div className="w-6 h-6 border-2 border-[var(--sky-primary)] border-t-transparent rounded-full animate-spin"></div>
                                    <span className="text-[10px] uppercase tracking-widest font-bold text-[var(--sky-primary)]">Syncing Geospatial Data...</span>
                                </div>
                            </div>
                        )}
                    </div>
                </div>

                {/* 55% Width Executive Intelligence Report */}
                <div className={`w-full lg:w-[55%] transition-opacity duration-300 ${isLoading ? 'opacity-50' : 'opacity-100'}`}>
                    <div className="bg-white rounded-2xl p-8 border border-[var(--slate-soft)] shadow-sm h-full max-h-[600px] overflow-y-auto custom-scrollbar">
                        
                        <div className="flex items-center justify-between mb-8 pb-4 border-b border-[var(--slate-soft)]">
                            <div>
                                <h3 className="text-lg font-sans font-bold text-[var(--navy-premium)]">Executive Intelligence Report</h3>
                                <p className="text-[10px] uppercase tracking-widest text-[var(--slate-medium)] font-bold mt-1">Generated by iSpine AI Core</p>
                            </div>
                            <span className="px-3 py-1 bg-[var(--sky-surface)] text-[var(--sky-primary)] text-[10px] font-bold uppercase tracking-widest rounded-md border border-[var(--sky-primary)]/10">
                                {selectedRegion.id}
                            </span>
                        </div>

                        <div className="space-y-8">
                            
                            {/* Sub-section */}
                            <div>
                                <h4 className="text-xs uppercase tracking-widest font-bold text-[var(--slate-medium)] mb-3 flex items-center gap-2">
                                    <span className="w-1 h-1 bg-[var(--sky-primary)] rounded-full"></span> Key Demographics
                                </h4>
                                <p className="text-sm font-medium text-[var(--navy-premium)] leading-relaxed">
                                    The {selectedRegion.name} region is characterized by a high density of working-class voters with a rising youth demographic. Our models indicate that 34% of the electorate here is composed of first-time or second-time voters, necessitating a digital-first outreach strategy.
                                </p>
                            </div>

                            {/* Sub-section */}
                            <div>
                                <h4 className="text-xs uppercase tracking-widest font-bold text-[var(--slate-medium)] mb-3 flex items-center gap-2">
                                    <span className="w-1 h-1 bg-[var(--sky-primary)] rounded-full"></span> Political Landscape
                                </h4>
                                <p className="text-sm font-medium text-[var(--navy-premium)] leading-relaxed">
                                    Historically highly contested, this region currently leans favorable due to recent policy announcements. However, anti-incumbency micro-clusters exist in the peripheral wards. 
                                </p>
                            </div>

                            {/* Sub-section */}
                            <div>
                                <h4 className="text-xs uppercase tracking-widest font-bold text-[var(--slate-medium)] mb-3 flex items-center gap-2">
                                    <span className="w-1 h-1 bg-[var(--sky-primary)] rounded-full"></span> Development Overview
                                </h4>
                                <div className="bg-[var(--sky-surface)] p-4 rounded-xl border border-[var(--sky-primary)]/10">
                                    <div className="flex justify-between items-center mb-2">
                                        <span className="text-[10px] uppercase tracking-widest font-bold text-[var(--navy-premium)]">Infrastructure Score</span>
                                        <span className="text-[10px] uppercase tracking-widest font-bold text-[var(--sky-primary)]">{selectedRegion.devIndex}/100</span>
                                    </div>
                                    <div className="w-full h-1.5 bg-white rounded-full overflow-hidden">
                                        <motion.div 
                                            initial={{ width: 0 }}
                                            animate={{ width: `${selectedRegion.devIndex}%` }}
                                            transition={{ duration: 1 }}
                                            className="h-full bg-[var(--sky-primary)]"
                                        />
                                    </div>
                                    <p className="text-xs font-medium text-[var(--slate-medium)] mt-3 leading-relaxed">
                                        Road connectivity and water supply have seen marked improvements, yet healthcare accessibility in the eastern quadrant remains a vulnerability that opposition forces may exploit.
                                    </p>
                                </div>
                            </div>

                            {/* Sub-section */}
                            <div>
                                <h4 className="text-xs uppercase tracking-widest font-bold text-[var(--slate-medium)] mb-3 flex items-center gap-2">
                                    <span className="w-1 h-1 bg-[var(--sky-primary)] rounded-full"></span> Campaign Intelligence
                                </h4>
                                <p className="text-sm font-medium text-[var(--navy-premium)] leading-relaxed">
                                    Ground mobilization is operating at {selectedRegion.readiness}% efficiency. Volunteer allocation must be increased by 15% to meet door-to-door coverage targets before the final campaign phase.
                                </p>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </section>
    );
}
